# Generated by Django 2.0.2 on 2018-04-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='created',
            new_name='pub_date',
        ),
    ]
